[project]
name = "eyeball-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mediapipe>=0.10.21",
    "opencv-contrib-python>=4.11.0.86",
    "pyautogui>=0.9.54",
    "screeninfo>=0.8.1",
]
